"""empty message

Revision ID: 297566639f7
Revises: e5d4a35c88
Create Date: 2015-02-07 16:19:24.984184

"""

# revision identifiers, used by Alembic.
revision = '297566639f7'
down_revision = 'e5d4a35c88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
