"""empty message

Revision ID: 2d2f9709426
Revises: 15c7f004f5f
Create Date: 2015-01-24 16:39:19.056121

"""

# revision identifiers, used by Alembic.
revision = '2d2f9709426'
down_revision = '15c7f004f5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    ### end Alembic commands ###
