"""empty message

Revision ID: 382cc890657
Revises: 7532fd8e94
Create Date: 2015-01-27 02:46:11.265986

"""

# revision identifiers, used by Alembic.
revision = '382cc890657'
down_revision = '7532fd8e94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('anonymous', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'anonymous')
    ### end Alembic commands ###
