"""empty message

Revision ID: 49e6907dd3
Revises: 297566639f7
Create Date: 2015-02-21 19:41:48.639569

"""

# revision identifiers, used by Alembic.
revision = '49e6907dd3'
down_revision = '297566639f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('interpretation', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'interpretation')
    ### end Alembic commands ###
