"""empty message

Revision ID: 594bea42235
Revises: 382cc890657
Create Date: 2015-01-27 04:04:53.956030

"""

# revision identifiers, used by Alembic.
revision = '594bea42235'
down_revision = '382cc890657'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    ### end Alembic commands ###
