"""empty message

Revision ID: 7532fd8e94
Revises: 2d2f9709426
Create Date: 2015-01-25 23:11:49.213744

"""

# revision identifiers, used by Alembic.
revision = '7532fd8e94'
down_revision = '2d2f9709426'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('anonymously', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('yourself', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_first_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=1)
    op.drop_column('user', 'timestamp')
    op.drop_column('post', 'yourself')
    op.drop_column('post', 'anonymously')
    ### end Alembic commands ###
