"""empty message

Revision ID: a4e42fbe84
Revises: 49e6907dd3
Create Date: 2015-02-22 16:36:15.202081

"""

# revision identifiers, used by Alembic.
revision = 'a4e42fbe84'
down_revision = '49e6907dd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('meta_description', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'meta_description')
    ### end Alembic commands ###
