"""empty message

Revision ID: e5d4a35c88
Revises: 20fe52eee5c
Create Date: 2015-02-07 16:14:42.479888

"""

# revision identifiers, used by Alembic.
revision = 'e5d4a35c88'
down_revision = '20fe52eee5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('article', 'text')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('article', 'content')
    ### end Alembic commands ###
